=== IT-Hock/fpm-repository/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "pattern": "^([a-z]+[a-z\\-\\_]+)$"
      },
      "description": {
        "type": "string",
        "pattern": "^([a-zA-Z0-9\\s\\-\\_\\,\\:\\;\\!\\?\\(\\)\\[\\]\\{\\}\\'\\\"]+)$|(/w+).md|(https:\\/\\/raw\\.githubusercontent\\.com/(.*?)\\.md)$"
      },
      "version": {
        "type": "string",
        "pattern": "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$"
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "author": {
        "type": "string"
      },
      "repository": {
        "type": "string",
        "pattern": "^https://github.com/(.*?)$"
      },
      "image":{
        "type": "string",
        "pattern": "^https:\\/\\/raw\\.githubusercontent\\.com/(.*?)\\.png"
      },
      "license": {
        "type": "string",
        "enum": [
          "MIT",
          "Apache-2.0",
          "BSD-2-Clause",
          "BSD-3-Clause",
          "GPL-2.0",
          "GPL-3.0",
          "LGPL-2.1",
          "LGPL-3.0",
          "MPL-2.0",
          "AGPL-3.0",
          "Unlicense"
        ],
        "default": "MIT"
      },
      "dependencies": {
        "type": "object",
        "patternProperties": {
          "^system\\.(.*?)$|^([a-z]+[a-z\\-\\_]+)$": {
            "type": "string",
            "pattern": "^(>=|<=|>|<|~|\\^)?([0-9]+)\\.([0-9]+)\\.([0-9]+)$"
          }
        }
      }
    },
    "required": [
      "name",
      "description",
      "image",
      "version",
      "tags",
      "author",
      "repository",
      "dependencies"
    ]
  }

=== IT-Hock/fpm-repository/example/fpm.json
{
    "$schema": "https://raw.githubusercontent.com/IT-Hock/fpm-repository/master/schema.json",
    "name": "my-awesome-plugin",
    "description": "https://raw.githubusercontent.com/johndoe/my-awesome-plugin/master/README.md",
    "image": "https://raw.githubusercontent.com/johndoe/my-awesome-plugin/master/screenshot.png",
    "version": "1.0.0",
    "tags": ["git", "productivity"],
    "author": "John Doe <j.doe@doe.com>",
    "repository": "https://github.com/johndoe/my-awesome-plugin",
    "license": "MIT",
    "dependencies": {
        "awesome": "1.0.0",
        "system.git": ">=1.7.0"
    }
}
